// Signup
export const SUBMIT_EMAIL_SUCCESS = 'SUBMIT_EMAIL_SUCCESS';
export const SUBMIT_EMAIL_FAIL = 'SUBMIT_EMAIL_FAIL';

// Podcast
export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_FAIL = 'GET_EPISODES_FAIL';
